-- MySQL Script generated by MySQL Workbench
-- Tue Nov 21 15:36:33 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema braintraining_forstudents
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema braintraining_forstudents
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `braintraining_forstudents` DEFAULT CHARACTER SET utf8 ;
USE `braintraining_forstudents` ;

-- -----------------------------------------------------
-- Table `braintraining_forstudents`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `braintraining_forstudents`.`users` (
  `id` INT AUTO_INCREMENT,
  `nickname` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `braintraining_forstudents`.`games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `braintraining_forstudents`.`games` (
  `id` INT AUTO_INCREMENT,
  `exercise` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `braintraining_forstudents`.`attemps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `braintraining_forstudents`.`attemps` (
  `id` INT AUTO_INCREMENT,
  `start_date` DATETIME NULL,
  `timer` TIME NULL,
  `nb_ok` INT NULL,
  `nb_total` INT NULL,
  `game_id` INT NOT NULL,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_attemps_games1_idx` (`game_id` ASC) VISIBLE,
  INDEX `fk_attemps_users1_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_attemps_games1`
    FOREIGN KEY (`game_id`)
    REFERENCES `braintraining_forstudents`.`games` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_attemps_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `braintraining_forstudents`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
